# Generated by Django 3.0.6 on 2020-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_release_date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
