# Generated by Django 3.0.6 on 2020-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0003_movieinfo_movie_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_test', models.CharField(max_length=200)),
            ],
        ),
    ]
