# Generated by Django 3.0.6 on 2020-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0002_auto_20200610_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='LAST Name'),
        ),
    ]
