# Generated by Django 3.0.6 on 2020-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0002_movieinfo_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_detail',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
