# Generated by Django 3.0.6 on 2020-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0004_auto_20200610_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password2',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
