# Generated by Django 3.0.6 on 2020-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0008_auto_20200601_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='faculty',
            field=models.CharField(choices=[('fass', 'Arts and Social Sciences'), ('biz', 'Business'), ('com', 'Computing'), ('den', 'Dentistry'), ('sde', 'Design and Environment'), ('eng', 'Engineering'), ('law', 'Law'), ('med', 'Medicine'), ('sci', 'Science')], default='biz', max_length=50),
        ),
    ]
