# Generated by Django 3.0.6 on 2020-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0012_auto_20200601_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_number',
            field=models.IntegerField(),
        ),
    ]
