# Generated by Django 3.0.6 on 2020-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0013_auto_20200601_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='faculty',
            field=models.CharField(choices=[('fass', 'Arts and Social Sciences'), ('biz', 'Business'), ('com', 'Computing'), ('den', 'Dentistry'), ('sde', 'Design and Environment'), ('eng', 'Engineering'), ('law', 'Law'), ('med', 'Medicine'), ('sci', 'Science')], default='sci', max_length=50),
        ),
    ]
