# Generated by Django 3.0.6 on 2020-06-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0014_auto_20200612_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
