# Generated by Django 3.0.6 on 2020-06-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0014_auto_20200601_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='faculty',
        ),
    ]
