# Generated by Django 3.0.6 on 2020-06-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0015_auto_20200613_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
