# Generated by Django 3.0.6 on 2020-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0016_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Outerwear', 'Outerwear'), ('Bottom', 'Bottom'), ('Laptop Accessories', 'Laptop Accessories'), ('Lifestyle', 'Lifestyle'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
