# Generated by Django 3.0.6 on 2020-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0016_userinfo_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
