# Generated by Django 3.0.6 on 2020-06-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0017_auto_20200613_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
