# Generated by Django 3.0.6 on 2020-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0019_auto_20200614_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_of_MERCH',
        ),
    ]
