# Generated by Django 3.0.6 on 2020-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0020_auto_20200614_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.CharField(choices=[('NIL', 'NIL'), ('Faculty', 'Faculty'), ('Matric', 'Matric'), ('Email', 'Email'), ('Campus Residential', 'Campus Residential')], default='NIL', max_length=200, null=True),
        ),
    ]
