# Generated by Django 3.0.6 on 2020-06-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0024_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter_campus',
            field=models.CharField(blank=True, choices=[('TH', 'Temasek Hall'), ('EH', 'Eusoff Hall'), ('SH', 'Sheares Hall'), ('RH', 'Raffles Hall'), ('KR', 'Kent Ridge Hall'), ('TEM', 'Tembusu'), ('RVRC', 'Ridge View Residences'), ('CAPT', 'College of Alice and Peter Tan'), ('USP', 'University Scholars Programme'), ('RC4', 'Residential College 4'), ('NIL', 'Do Not Stay On Campus')], max_length=200, null=True, verbose_name='Filter(Campus)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_email',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Filter(Email)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_faculty',
            field=models.CharField(blank=True, choices=[('FASS', 'Arts and Social Sciences'), ('BIZ', 'Business'), ('COM', 'Computing'), ('DEN', 'Dentistry'), ('SDE', 'Design and Environment'), ('ENG', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('SCI', 'Science')], max_length=200, null=True, verbose_name='Filter(Faculty)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_matric',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Filter(Matric)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Image**'),
        ),
    ]
