# Generated by Django 3.0.6 on 2020-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0025_auto_20200616_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizing',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Sizing Chart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Photo of MERCH**'),
        ),
    ]
