# Generated by Django 3.0.6 on 2020-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0026_auto_20200617_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_email',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Filter(NUSNET ID)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.URLField(verbose_name='Order Form'),
        ),
    ]
