# Generated by Django 3.0.6 on 2020-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0028_auto_20200620_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backview',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Backview of MERCH'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100000, null=True, verbose_name='Description/Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_email',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Filter(NUSNET ID)*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_matric',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Filter(Matric)*'),
        ),
    ]
