# Generated by Django 3.0.6 on 2020-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0029_auto_20200720_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iglink',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram AD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizing',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Sizing Chart'),
        ),
    ]
