# Generated by Django 3.0.6 on 2020-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0030_auto_20200722_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='iglink',
            field=models.URLField(null=True, verbose_name='Instagram AD'),
        ),
    ]
