# Generated by Django 3.0.6 on 2020-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmerch', '0031_auto_20200723_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backview',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Backview of MERCH'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iglink',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram AD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizing',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Sizing Chart'),
        ),
    ]
